# Generated by Django 2.2.2 on 2019-06-30 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("portal", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="BusinessStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="BusinessType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(model_name="business", name="category"),
        migrations.RemoveField(model_name="business", name="compliance"),
        migrations.RemoveField(model_name="business", name="organisation_type"),
        migrations.AlterField(
            model_name="business",
            name="registration_number",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="portal.BusinessStatus"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="business_type",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="portal.BusinessType",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="business",
            name="sector",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="portal.Sector",
            ),
            preserve_default=False,
        ),
    ]
