# Generated by Django 2.2.2 on 2019-06-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20190630_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='region',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portal.Region'),
            preserve_default=False,
        ),
    ]
