# Generated by Django 2.2.2 on 2019-07-04 14:47

import colorful.fields
import django.db.models.deletion
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Municipality = apps.get_model("portal", "Municipality")
    db_alias = schema_editor.connection.alias
    Municipality.objects.using(db_alias).bulk_create(
        [Municipality(mdb_code="WC033", label="Cape Agulhas")]
    )


class Migration(migrations.Migration):

    dependencies = [("portal", "0004_auto_20190630_1342")]

    operations = [
        migrations.CreateModel(
            name="Municipality",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mdb_code", models.CharField(max_length=10, unique=True)),
                ("label", models.CharField(max_length=200)),
                ("color", colorful.fields.RGBColorField(colors=["#4498C6"])),
            ],
        ),
        migrations.RunPython(forwards_func),
        migrations.AddField(
            model_name="region",
            name="municipality",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regions",
                to="portal.Municipality",
            ),
            preserve_default=False,
        ),
    ]
