# Generated by Django 2.2.2 on 2019-07-07 11:02

import django.db.models.deletion
from django.db import migrations, models


def add_site(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    db_alias = schema_editor.connection.alias
    Site = apps.get_model("sites", "Site")
    Site.objects.using(db_alias).bulk_create(
        [Site(domain="biz.capeagulhas.org", name="Cape Agulhas Business Portal")]
    )


def add_muni(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Municipality = apps.get_model("portal", "Municipality")
    Site = apps.get_model("sites", "Site")
    site = Site.objects.get(domain="biz.capeagulhas.org")
    Municipality.objects.using(db_alias).bulk_create(
        [Municipality(mdb_code="WC033", label="Cape Agulhas", site=site)]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("portal", "0004_auto_20190630_1342"),
    ]

    operations = [
        migrations.RunPython(add_site),
        migrations.CreateModel(
            name="Municipality",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mdb_code", models.CharField(max_length=10, unique=True)),
                ("label", models.CharField(max_length=200)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.Site"
                    ),
                ),
            ],
            options={"verbose_name_plural": "municipalities"},
        ),
        migrations.RunPython(add_muni),
        migrations.AddField(
            model_name="region",
            name="municipality",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regions",
                to="portal.Municipality",
            ),
            preserve_default=False,
        ),
    ]
