# Generated by Django 2.2.2 on 2019-07-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("portal", "0005_auto_20190707_1102")]

    operations = [
        migrations.AddField(
            model_name="municipality",
            name="logo",
            field=models.CharField(
                blank=True,
                help_text="e.g. images/logo-WC033.png",
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="label",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
