# Generated by Django 2.2.2 on 2019-07-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("portal", "0005_auto_20190704_1447")]

    operations = [
        migrations.AlterModelOptions(
            name="municipality", options={"verbose_name_plural": "municipalities"}
        )
    ]
