# Generated by Django 2.2.2 on 2019-07-04 16:55

import django.db.models.deletion
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Site = apps.get_model("sites", "Site")
    db_alias = schema_editor.connection.alias
    Site.objects.using(db_alias).bulk_create(
        [Site(domain="example.com", name="Example Site Name")]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("portal", "0006_auto_20190704_1459"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
        migrations.AddField(
            model_name="municipality",
            name="site",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="sites.Site"
            ),
            preserve_default=False,
        ),
    ]
