# Generated by Django 2.2.2 on 2019-07-05 21:46

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("portal", "0007_municipality_site")]

    operations = [
        migrations.AlterField(
            model_name="municipality",
            name="color",
            field=colorful.fields.RGBColorField(colors=["#4498C6"], default="#4498C6"),
        )
    ]
