# Generated by Django 2.2.2 on 2019-07-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("portal", "0007_auto_20190711_1822")]

    operations = [
        migrations.RenameField(
            model_name="municipality",
            old_name="add_details_url",
            new_name="add_update_business_url",
        ),
        migrations.RemoveField(model_name="municipality", name="claim_business_url"),
    ]
