# Generated by Django 2.2.2 on 2019-07-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("portal", "0010_auto_20190712_1331")]

    operations = [
        migrations.RenameField(
            model_name="business",
            old_name="physical_address",
            new_name="registered_physical_address",
        ),
        migrations.RenameField(
            model_name="business",
            old_name="postal_address",
            new_name="registered_postal_address",
        ),
        migrations.RenameField(
            model_name="business", old_name="status", new_name="registration_status"
        ),
    ]
