# Generated by Django 2.2.2 on 2019-07-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("portal", "0011_auto_20190712_1334")]

    operations = [
        migrations.RenameField(
            model_name="business",
            old_name="business_type",
            new_name="registered_business_type",
        )
    ]
