# Generated by Django 2.2.2 on 2019-07-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("portal", "0012_auto_20190712_1336")]

    operations = [
        migrations.AlterField(
            model_name="municipality",
            name="add_update_business_url",
            field=models.CharField(
                blank=True,
                help_text="Public URL for the form where businesses can request for their business details to be added or updated",
                max_length=500,
                verbose_name="Add/Update Business form URL",
            ),
        )
    ]
