# Generated by Django 2.2.2 on 2019-07-12 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("portal", "0014_auto_20190712_2045")]

    operations = [
        migrations.AddField(
            model_name="business",
            name="date_started",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="supplied_physical_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="business",
            name="supplied_postal_address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="businesses",
                to="portal.Region",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="registered_business_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="businesses",
                to="portal.BusinessType",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="registered_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="business",
            name="registered_physical_address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="registered_postal_address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="registration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="registration_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="businesses",
                to="portal.BusinessStatus",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="businesses",
                to="portal.Sector",
            ),
        ),
    ]
