# Generated by Django 2.2.2 on 2019-07-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("portal", "0015_auto_20190712_2126")]

    operations = [
        migrations.AddField(
            model_name="business",
            name="supplied_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="business",
            name="registration_number",
            field=models.CharField(
                help_text="This should only be modified if it was initially entered incorrectly.",
                max_length=200,
                unique=True,
            ),
        ),
    ]
