# Generated by Django 2.2.2 on 2019-07-13 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("portal", "0016_auto_20190713_0638")]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="businesses",
                to="portal.Region",
            ),
        )
    ]
