# Generated by Django 2.2.2 on 2019-07-13 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portal", "0017_auto_20190713_0645"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipality",
            name="administrators",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        )
    ]
