# Generated by Django 2.2.2 on 2019-07-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("portal", "0019_auto_20190715_1140")]

    operations = [
        migrations.AddField(
            model_name="business",
            name="email_address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="municipality",
            name="email_address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="cellphone_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="facebook_page_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="fax_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="instagram_page_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="phone_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="supplied_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="supplied_physical_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="supplied_postal_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="twitter_page_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="website_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="add_update_business_url",
            field=models.CharField(
                blank=True,
                help_text="Public URL for the form where businesses can request for their business details to be added or updated",
                max_length=500,
                null=True,
                verbose_name="Add/Update Business form URL",
            ),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="cellphone_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="facebook_page_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="fax_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="instagram_page_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="logo",
            field=models.CharField(
                blank=True,
                help_text="e.g. images/logo-WC033.png",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="phone_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="special_instructions",
            field=models.TextField(
                blank=True,
                help_text="Special instructions for contacting the municipality in relation to their business portal",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="twitter_page_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="website_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
