# Generated by Django 2.2.2 on 2019-07-18 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("portal", "0019_auto_20190715_1140")]

    operations = [
        migrations.CreateModel(
            name="BusinessMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("censored_id_number", models.CharField(max_length=200)),
                ("first_names", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                (
                    "position",
                    models.IntegerField(
                        choices=[
                            (1, "Member"),
                            (2, "Director"),
                            (3, "Alternate Director"),
                            (4, "Company Secretary"),
                        ]
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="portal.Business",
                    ),
                ),
            ],
        )
    ]
