# Generated by Django 2.2.2 on 2019-07-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("portal", "0020_auto_20190718_1320")]

    operations = [
        migrations.AddField(
            model_name="municipality",
            name="linkedin_page_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        )
    ]
