# Generated by Django 2.2.2 on 2019-07-23 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_auto_20190723_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='portal.Sector'),
        ),
    ]
