# Generated by Django 2.2.2 on 2019-07-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0022_municipality_google_analytics_code"),
        ("portal", "0023_auto_20190723_1030"),
    ]

    operations = []
