# Generated by Django 2.2.2 on 2019-09-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("portal", "0025_businessmembership")]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="icon_name",
            field=models.CharField(blank=True, max_length=200),
        )
    ]
